controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_vente_deformations: # Correction du nom de la route
    path: '/vente-de-formations' # Correction du chemin de l'URL
    controller: 'App\Controller\VenteDeformationsController::index'

download_pdf:
    path: '/compte/download-pdf/{id}'
    controller: 'App\Controller\ConsulterCesFormationsController::downloadPdf'

app_panier:
    path: '/compte/panier' # Ajout du slash au début du chemin de l'URL
    controller: 'App\Controller\PanierController::index'
